/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class TextureGenerator {
  constructor(width: number, height: number)
  /** Generate a procedural texture (gradient pattern) */
  generateGradient(): Buffer
  /** Generate a checkerboard pattern */
  generateCheckerboard(squareSize: number): Buffer
  /** Generate a plasma effect */
  generatePlasma(time: number): Buffer
  getWidth(): number
  getHeight(): number
}
