/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Directory information */
export interface DirectoryInfo {
  name: string
  path: string
  isDirectory: boolean
  children: Array<DirectoryInfo>
}
/**
 * Return a directory tree rooted at the queried path. The root contains its immediate
 * child directories in `children`, and each child contains its own immediate children
 * (depth = 2). Hidden entries (starting with a dot) are skipped. Not recursive.
 */
export declare function getDirChildren(relativePath: string): DirectoryInfo
/** Photo information returned to the JS side */
export interface PhotoInfo {
  name: string
  nativeRender: boolean
}
/**
 * Given an absolute directory path, return a sorted list of files in that
 * directory which match common image file extensions. Each returned item
 * includes the file name and a `native_render` flag (hardcoded to false).
 */
export declare function getDirPhotos(absolutePath: string): Array<PhotoInfo>
/** Processed photo information */
export interface ThumbnailInfo {
  dataBase64: string
  thumbWidth: number
  thumbHeight: number
  fullWidth: number
  fullHeight: number
}
/**
 * Generate a processed photo for the provided absolute image path. The image is scaled down
 * to fit within the provided `max_w` x `max_h` constraint while preserving aspect ratio
 * (no upscaling). Returns a base64-encoded PNG buffer and both processed and full-size dimensions.
 */
export declare function getProcessedPhoto(absolutePath: string, maxW: number, maxH: number): ThumbnailInfo
/** Full-size image information */
export interface FullImageInfo {
  dataBase64: string
  width: number
  height: number
}
/** Return the full-size image encoded as PNG and base64-encoded. */
export declare function getFullImage(absolutePath: string): FullImageInfo
export declare class TextureGenerator {
  constructor(width: number, height: number)
  /** Generate a procedural texture (gradient pattern) */
  generateGradient(): Buffer
  /** Generate a checkerboard pattern */
  generateCheckerboard(squareSize: number): Buffer
  /** Generate a plasma effect */
  generatePlasma(time: number): Buffer
  getWidth(): number
  getHeight(): number
}
